### ISSUE TITLE
Message formatting

### ISSUE THREAD

**Issue by subliun** [Tox/Tox-Client-Standard#19]
https://github.com/Tox-Archive/Tox-STS/issues/74

Together we can rewrite the STS.

**Comment by optimumtact** [comment]
:+1: to a light markdown support

mainly because it will degrade reasonably gracefully when not implemented.

**Comment by tux3** [comment]
:+1: to this, if it's standardized across all clients I'd be much happier to implement it.

**Comment by nurupo** [comment]
@tux3 you are willing to pull webkit as qtox dependency for this? : ) Otherwise how are you going to implement it, I'm curious.

**Comment by tux3** [comment]
@nurupo Technically I think Qt already embeds some Webkit version, but I don't need webkit to grep for pairs of symbols. Light markdown is trivial to parse.

**Comment by nurupo** [comment]
Well, then you should standardize what you mean by "light markdown". Do you allow tables, inline images, raw text blocks, code highlights, etc? Looking at the STS issue, some people were proposing to use gh-flavored markdown.

**Comment by tux3** [comment]
I'm probably not going to do tables, that seem way overkill for a chat client, but basic things like em/strong/strikethrough and maybe raw text are definitely easy to do.

If we want to standardize something, I think it would be a good idea to start small and then maybe think about extending it. 
If you require all the clients to support markdown tables and code highlighting, it's obviously not going to work. But if Tox adopts some light markdown formatting, I think it'll be a really cool feature for users.

**Comment by stal888** [comment]
I think **bold**, _italic_, and underlines are a good feature set to start with.

**Comment by tux3** [comment]
Underline is nice, but it isn't officially in markdown. What symbol would you use for it?

**Comment by GrayHatter** [comment]
```
_underline_ 
~strikeout~
/italics/
*bold*
```

**Comment by rugk** [comment]
:+1: for lightweight markdown

BTW the Ricin client already implements it: https://github.com/RicinApp/Ricin/issues/30

**Comment by GrayHatter** [comment]
I suggest we adapt https://help.github.com/articles/markdown-basics/ as our markdown of choice. Per wikipedia, there's no standard, so because we all use github, a lot of the usage/testing will be programmers. Github's flavor is least likely to aggravate us.

**Comment by rugk** [comment]
There is no standard, but the basic things were invented by John Gruber (according to Wikipedia) and he documented it here: https://daringfireball.net/projects/markdown/

So anyone can take this as a reference. Of course you can add additional things like GitHub does with [GitHub Flavored Markdown](https://help.github.com/articles/github-flavored-markdown/), but (except of strikethrough and autolinking of URLs) this is not a thing for a lightweight markdown.  
https://help.github.com/articles/markdown-basics/ also shows the basic markdown like it was done by John Gruber.

**Comment by TheNain38** [comment]
:+1:

**Comment by GrayHatter** [comment]
@rugk I thought about that, but again per wikipedia, he's no longer maintaining it, so he no longer gets a vote.

**Comment by rugk** [comment]
He set the standard and this standard was adopted (and extended) by many organisations, so it does not matter whether he "maintains" it.

BTW where in the Wikipedia article is it stated that he does not maintain it? (Okay the last release of the software was in 2004, but it does not matter as we do not need the source code he wrote anyway - the spec is the thing which matters.)

**Comment by SkyzohKey** [comment]
My approach to implement a lite-version of Markdown (which I called LiteMD) was this one (using simple regex):

``` vala
// Vala code from RicinApp/Ricin by SkyzohKey
public static string render_litemd (string text) {
  var bold = /\B\*\*([^\*\*]*)\*\*\B/.replace (text, -1, 0, "<b>\\1</b>");
  var italic = /\b_([^_]*)_\b/.replace(bold, -1, 0, "<i>\\1</i>");
  var underline = /\B-([^-]*)-\B/.replace(italic, -1, 0, "<u>\\1</u>");
  var striked = /\B~([^~]*)~\B/.replace(underline, -1, 0, "<s>\\1</s>");

  var final_text = striked;
  return final_text;
}
```

Basically I just replace some expressions by their HTML equivalent (ie. `**text**` became `<b>text</b>`) then return the value. GTK do the job to render HTML in the UI widget for messages and it's all.

I think we should provide the following Markdown "tags" : 
- `**text**` or `*text*` → **Bold** ;
- `//text//` or `/text/` → _Italic_ ;
- `__text__` or `_text_` → <ins>Underline</ins> ;
- `~~text~~` or `~text~` → ~~Strike-through~~ ;

\+ Code formatting (using GtkSourceView or the equivalent in Qt) : 

``` js
``language-to-highlight
var hello = "Hello, world!";
console.log(hello);
``
```

Lists/Tables would be shitty to implement. I think we shouldn't support them.

\+ Maybe that Markdown could be used to have a proper quoting format. Something like:

```
@SkyzohKey (31 Dec 2015, 13:02 GMT+1)
> This is a nice quoting format, I guess.
> Clients would parse the first line to get all the important data. Then display them.
This line isn't a quote so it's not formatted.
```

**Comment by rugk** [comment]
@SkyzohKey 

IMO this is not really such a good implementation as it is not standard markdown. E.g. usually `*text` results in italic _text_ and not bold one.
Also for code formatting I would use three ``` like it is done in GitHub Flavored Markdown.

Quoting with `>` is a good idea as it is also standard markdown - except that you need an empty line after a quote to finish it:

```
> This is a nice quoting format, I guess.
> Clients would parse the first line to get all the important data. Then display them.

This line isn't a quote so it's not formatted.
```

**Comment by DanTheBritish** [comment]
:+1: For @SkyzohKey and @GrayHatter standard

**Comment by rugk** [comment]
[**@LapFox**](https://github.com/LapFox) commented on [3. Jan. 2016, 16:27 MEZ](https://github.com/Tox/Tox-Client-Standard/issues/19#issuecomment-168505405 "2016-01-03T15:27:13Z - Replied by Github Comment Enhancer"):
> :+1:(https://assets-cdn.github.com/images/icons/emoji/unicode/1f44d.png ":+1:") For [@SkyzohKey](https://github.com/SkyzohKey) and [@GrayHatter](https://github.com/GrayHatter) standard

What? As I said the standards @SkyzohKey and @GrayHatter suggested are completely different.

**Comment by GrayHatter** [comment]
I think he means either. As is, just implement markdown of any kind

**Comment by stal888** [comment]
We should stay with the GFM or CommonMark specs.

**Comment by rugk** [comment]
@stal888 :+1:
