### ISSUE TITLE
Avatar storage

### ISSUE THREAD

**Issue by tux3** [Tox/Tox-Client-Standard#22]
I have a couple questions about the section on avatars.

> If the client supports user avatars, they will be stored under the avatars/ directory in the root of the client's working directory.

The "client's working directory" is the data/configuration directory, not the working directory of the application, I assume? Maybe this could be reworded.

> Avatars are named according to the following format: PK.png, where PK is the 64-character hexadecimal public key of its owner.

Now storing avatars in this way might be a privacy issue, or at least a surprise for people who use encrypted Tox profiles.
- If I have an unique encrypted profile, you can see the list of my contacts (as long as they have avatars) just by looking in this folder, this is probably not what encrypted profile users expect
- The avatars of my contacts may be sensitive, if this implies that avatar must be stored unencrypted (does it?), you could probably tell what kind of people I talk to by their avatars
- If profile A is unencrypted and profile B is encrypted, A can tell what contacts B has that A doesn't have by looking in the avatar directory.

Instead I think that for encrypted profiles Tox clients should be required to store avatars encrypted in some other location of their choosing (since encryption isn't portable between clients) and without revealing the public key of the contacts.

**Comment by nurupo** [comment]
> > Avatars are named according to the following format: PK.png, where PK is the 64-character hexadecimal public key of its owner.
> 
> Now storing avatars in this way might be a privacy issue, or at least a surprise for people who use encrypted Tox profiles

That's from Export Format section, it describes only the export format. Your client may store avatars in any way you want with any names you want, you might as well put them in SQLite database and encrypt the entire database, but when exporting, you should provide avatars in the format specified, so that another client could import them. Avatars should have public keys to them attached one way or another, so that the importing client would know which avatar belongs to whom.

**Comment by nurupo** [comment]
I'm not even sure if it's allowed to export an encrypted with libtoxencryptsave data file, the document doesn't say any specifics. If it's allowed, it might make sense to somehow encrypt avatars, not just the file-names, but also the images themselves.

**Comment by tux3** [comment]
Thanks, that makes more sense. I somehow didn't see it was about exporting.

Though, wouldn't it make sense to let the user choose where to export instead of always exporting in the current working directory?
IIRC on Windows the working directory would likely be in Program Files, which I think isn't writable without a UAC prompt (correct me if I'm wrong).

**Comment by nurupo** [comment]
Yeah, I no idea what "working directory" means here and why it's used. Maybe someone who wrote this could tell us.

**Comment by SkyzohKey** [comment]
Why not simply hashing the avatar name using a standard algorithm (say `sha1`) then storing them in `~/.config/tox/avatars` ? This way each client would just have to hash the friend's pubkey and look for it in the `avatars/` dir. This would permit to save disk space (even minimal one) by allowing multiple clients to use the same image.

**Comment by tux3** [comment]
(so github has a new beta UI that shows all my open issues.. I think this one is closeable =] )

**Comment by Zer0-One** [comment]
Is there a sign out the front of my house that says "dead avatar storage"?
