### ISSUE TITLE
Connect the repo to Reviewable

### ISSUE THREAD

**Issue by SkyzohKey** [Tox/Tox-Client-Standard#29]
Please connect this repo at https://reviewable.io/repositories so that all PRs get linked to reviews. Thanks!

**Comment by nurupo** [comment]
Why do we want this?

**Comment by JFreegman** [comment]
This is unnecessary because the standard committee already reviews pull requests.

**Comment by SkyzohKey** [comment]
Reviewable make it easy to review changes in a more convenient way.

**Comment by GrayHatter** [comment]
Reviewable does actually make it really nice. But I'm torn, it's very verbose and once you start in reviewable using only github is problematic.

**Comment by SkyzohKey** [comment]
Hmm, yeah. :x
