### ISSUE TITLE
The vote on the requests

### ISSUE THREAD

**Issue by alexeysvrv** [Tox/Tox-Client-Standard#31]
I suggest, make a list of people who should vote for the fusion or rejection PR. I believe that this should be the developers of all clients, toxcore and the most active users-contributors. Otherwise, the adoption of new requests (and the older too) can be delayed for a very long time. The most important fundamental changes I propose to bring to the community vote

**Comment by alexeysvrv** [comment]
@Zer0-One @JFreegman @nurupo @grayhatter @irungentoo @Impyy @tux3 @iphydf @mannol @SkyzohKey @wiiaam

**Comment by alexbakker** [comment]
We already have such a list: https://wiki.tox.chat/about/committees

**Comment by alexeysvrv** [comment]
@Impyy Yes, but now in a hung state PR and their authors point to a different number of voting

**Comment by alexbakker** [comment]
What does that mean? 'different number of voting'?

**Comment by alexeysvrv** [comment]
@Impyy Sorry(Google Translate). In different PR of their authors ask voices of different people

**Comment by alexbakker** [comment]
Everyone's voice is heard. But in the end, the list of the people who actually vote stays the same (i.e. the committee members).
