### ISSUE TITLE
Standard encryption method

### ISSUE THREAD

**Issue by SkyzohKey** [Tox/Tox-Client-Standard#32]
Currently their is no "standard" way to use ToxES. I mean, clients developers don't know if they should use `tox_derive_key_with_salt`,  `tox_derive_key_from_pass`, etc. Also, if using a salt is the standard, maybe would it be nice to specify a _standard_ salt?

**Comment by stal888** [comment]
Why even use a salt if everyone's using the same salt?

**Comment by SkyzohKey** [comment]
@stal888 That's what I'm asking for a standard about that x)

**Comment by GrayHatter** [comment]
You don't need a standard. you don't salt a singles encrypted file. Salts solve rainbow tables, you don't rainbow table a file (unless you have a case of the dumbs). 

@SkyzohKey the standard way is to use `part 2` from the toxencryptsave.h file. There's no need to do key derivation unless you have to encrypt a lot of smaller files, and then you only need to for the performance boost.

**Comment by SkyzohKey** [comment]
@GrayHatter That was what I was asking for, thanks. :)
