### ISSUE TITLE
Reinstating the "DNS discovery" section of Tox-STS

### ISSUE THREAD

**Issue by intelfx** [Tox/Tox-Client-Standard#33]
Where is the [User Discovery](https://github.com/Tox-Archive/Tox-STS/blob/master/STS.md#user-discovery) section of the now-archived Tox STS; why it is not included here in some way?

If it had been made obsolete, what is the replacement for the DNS discovery?

**Comment by JFreegman** [comment]
The Tox Project doesn't officially support any third party services. Reasons for this are made clear in the rationale section, point 1.0.4.

Most clients use HTTPS based lookups now via toxme.io.
