### ISSUE TITLE
Clients should store data in XDG base directories

### ISSUE THREAD

**Issue by haavard** [Tox/Tox-Client-Standard#34]
The current standard recommends that Unix-like systems store Tox profile data files under `~/.config/tox/`. This seems like a half-hearted attempt at following the [XDG Base Directory Specification][1]. A very half-hearted attempt, as `~/.config/` is meant for *configuration* files, not data files.

I propose that clients should instead be recommended to follow the XDG specification proper, and store Tox profiles under `$XDG_DATA_HOME/tox/`. This is equivalent to `$HOME/.local/share/tox/` when the environment variable is unset or empty.

[1]: https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by nurupo** [comment]
This makes sense to me. User-specific configuration files go to `$XDG_CONFIG_HOME/tox`, with default fallback in the case of `$XDG_CONFIG_HOME` not being defined to `$HOME/.config/tox` and user-specific data files, like the Tox profile file, go to `$XDG_DATA_HOME/tox`, with default fallback in the case of `$XDG_DATA_HOME` not being defined to `$HOME/.local/share`.

- qTox: @tux3
- uTox: @GrayHatter, @robinlinden
- Ricin: @SkyzohKey
- Toxygen: @ingvar1995
- Toxic: @Jfreegman

Do you guys have any comments on this?

**Comment by SkyzohKey** [comment]
@nurupo @haavard :+1: for this, seems good to me.

**Comment by robinlinden** [comment]
Following the XDG spec sounds like a good idea. No complaints from me.

**Comment by sudden6** [comment]
Just found this and highly agree.

- Venom: @naxuroqa

**Comment by naxuroqa** [comment]
Agree as well :+1:
