### ISSUE TITLE
Too many catgirls are dying on the streets because of lack of infrastructure

### ISSUE THREAD

**Issue by subliun** [Tox/Tox-Client-Standard#7]
Did you know, that in 2014 alone there were **over 2,500** known catgirl deaths in the GTA? Time and time again the Harper government ignores this. Make a difference by electing Tom Mulcair's NDP® on October 19th.

**Comment by installgen2** [comment]
![spurdo_sparde_vector_by_kevinino-d6ehtjk](https://cloud.githubusercontent.com/assets/11202492/10538130/53bec2b4-73ee-11e5-85c6-3dbdb7b2857c.png)

## Dear sublium, please take your issue, and shove it deeply inside your anal cavity.

**Comment by subliun** [comment]
The issue was not resolved.

**Comment by installgen2** [comment]
@subliun your face was not resolved
